# -*- coding: utf-8 -*-
"""FindCompoundInterest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iyKskmsHmuKlGe9If5TFL0AxGQwVFC54
"""

# Function to compute the compound interest:

def compound_interest(principal, rate, time):
    """Compute the compound interest."""
    amount = principal * (1 + rate / 100) ** time
    compound_i = amount - principal
    return compound_i

FindCompoundInterest = compound_interest(1000, 10, 5)

print(FindCompoundInterest)